# --- 패닉 ---

프로그램이 잘못되어 에러가 발생한 뒤 종료되는 상황을 패닉이라고 함

```js
a := [...]int{1, 2}

for i := 0; i < 3; ++i {
    fmt.Println(a[i]) // 패닉 발생
}
```

## [ 패닉 다루기 ]

### - `panic(errorMsg)`

사용자가 패닉 발생시킴

```go
func main() {
    panic("Error!!")
    fmt.Println("Hello, world!")
}
/*  
panic: Error !!
*/
```

### - `recover()`

패닉이 발생하면 프로그램이 바로 종료되지 않고 예외처리할 수 있음(try~catch)

recover 함수는 지연 호출로 사용해야 함

패닉 함수에서 설정한 에러 메시지를 받아옴

```go
package main

import "fmt"

func f() {
	defer func() {
		s := recover()

		fmt.Println(s)
	}()

	panic("OMG!")
}

func main() {
	f()

	fmt.Println("Hello, world!") // 패닉이 발생했지만 계속 실행됨
}

/*
OMG!
Hello, world!
*/
```

